basePath: /api/v1
definitions:
  User:
    properties:
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
  pkg_users.UserModelValidator:
    properties:
      user:
        properties:
          email:
            type: string
          password:
            maxLength: 255
            minLength: 8
            type: string
          username:
            maxLength: 255
            minLength: 4
            type: string
        required:
        - email
        - password
        - username
        type: object
    type: object
host: localhost:8080
info:
  contact:
    email: kacperkrol99@icloud.com
    name: Kacper Król
  description: This is an API for TimeTrove application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: TimeTrove API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Retrieves all users from the database
      produces:
      - application/json
      responses:
        "200":
          description: Returns list of users
          schema:
            items:
              $ref: '#/definitions/User'
            type: array
      summary: Get Users
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Creates single user in database
      parameters:
      - description: User Object
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/pkg_users.UserModelValidator'
      produces:
      - application/json
      responses:
        "200":
          description: Returns Created User
          schema:
            $ref: '#/definitions/User'
      summary: Create User
      tags:
      - user
schemes:
- http
- https
securityDefinitions:
  JWT:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
